# Generated by Django 6.1.1 on 2026-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code Snippet', 'verbose_name_plural': 'Code Snippets'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Write your article using the rich text editor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Enter tags separated by commas (e.g., webdev, javascript, tutorial)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter the article title', max_length=200),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(help_text='Paste your code here'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of what this code does'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(help_text='e.g., python, javascript, css', max_length=50),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', unique=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Enter tags separated by commas (e.g., algorithm, performance)'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(help_text='Enter the snippet title', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the media'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Or upload an image', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', unique=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(help_text='Enter the media title', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Select media type', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(help_text='Full details (use the rich text editor)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project screenshot or image', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='Enter technologies separated by commas (e.g., React, Node.js, MongoDB)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Enter the project title', max_length=200),
        ),
    ]
